install.packages('ggfortify')
library('ggfortify')
df4 <- read.csv('/Users/alielassche/documents/github/cultural-analytics/songlyrics/posneg.csv', header = TRUE, row.names = 'Artist', sep = ';')
autoplot(prcomp(df4), loadings = TRUE, label = TRUE, label.size = 3, shape = FALSE, loadings.label = TRUE, loadings.label.size = 3, loadings.colour = 'blue')
df3 <- read.csv('/Users/alielassche/documents/github/cultural-analytics/songlyrics/wordtypes.csv', header = TRUE, row.names = 'Artist', sep = ';')
autoplot(prcomp(df3), loadings = TRUE, label = TRUE, label.size = 3, shape = FALSE, loadings.label = TRUE, loadings.label.size = 3, loadings.colour = 'blue')
df2 <- read.csv('/Users/alielassche/documents/github/cultural-analytics/songlyrics/emotions.csv', header = TRUE, row.names = 'Artist', sep = ';')
autoplot(prcomp(df2), loadings = TRUE, label = TRUE, label.size = 3, shape = FALSE, loadings.label = TRUE, loadings.label.size = 3, loadings.colour = 'blue')
df1 <- read.csv('/Users/alielassche/documents/github/cultural-analytics/songlyrics/commoncategories.csv', header = TRUE, row.names = 'Artist', sep = ';')
autoplot(prcomp(df1), loadings = TRUE, label = TRUE, label.size = 3, shape = FALSE, loadings.label = TRUE, loadings.label.size = 3, loadings.colour = 'blue')
df <- read.csv('/Users/alielassche/documents/github/cultural-analytics/songlyrics/artist_liwc_clean.csv', header = TRUE, row.names = 'Artist', sep = ';')
autoplot(prcomp(df), loadings = TRUE, label = TRUE, label.size = 3, shape = FALSE, loadings.label = TRUE, loadings.label.size = 3, loadings.colour = 'blue')
